defaults:
  - hydra: default
  - env: default
  - log: default

worker: eval_linprobe
output_dir: checkpoints
job_name: linprobe
pretrain_job_name:
checkpoint:
encoder_prefix: 'encoder.'
pretrain_resume_epoch: latest
eval: False
debug: False

model:
  image:
    backbone: vit_base
    pretrained: vit_base_mae_in1k
  audio:
    backbone: vit_base
    pretrained: vit_base_audiomae_as2m
  fusion:
    arch: factorized_mmi
    layers: all
    num_fusion_tkns: 16
    num_aggr_image_tkns: 8
    num_aggr_audio_tkns: 8
    mlp_ratio: 4.0
    attn_ratio: 0.25
    num_heads: 12

opt:
  resume: True
  use_amp: False
  batch_size: 64
  epochs: 60
  warmup_epochs: 10
  accum_iter: 4
  clip_grad:
  weight_decay: 0.0
  lr:
  blr: 0.3
  min_lr: 0.

data:
  dataset: vggsounds
  data_path: /srv/home/groups/pmorgado/datasets/vggsounds
  audio_rate: 16000
  audio_dur: 3.
  audio_mels: 128
  image_size: 224
  crop_min: 0.5
