wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736612083.549341
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 5
      - 13
      - 14
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 5
      - 9
eval:
  desc: null
  value: false
debug:
  desc: null
  value: false
opt.lr:
  desc: null
  value: 0.0006
worker:
  desc: null
  value: eval_finetune
env.gpu:
  desc: null
  value: null
opt.blr:
  desc: null
  value: 0.0003
env.ngpu:
  desc: null
  value: 4
env.node:
  desc: null
  value: localhost
env.port:
  desc: null
  value: 50001
env.rank:
  desc: null
  value: 0
env.seed:
  desc: null
  value: null
job_name:
  desc: null
  value: finetune_vggsound
env.slurm:
  desc: null
  value: true
log.debug:
  desc: null
  value: false
checkpoint:
  desc: null
  value: null
data.mixup:
  desc: null
  value: 1
env.mem_gb:
  desc: null
  value: 240
opt.epochs:
  desc: null
  value: 100
opt.min_lr:
  desc: null
  value: 0
opt.resume:
  desc: null
  value: true
output_dir:
  desc: null
  value: /home/wiss/zverev/DeepAVFusion/checkpoints/deepavfusion_vitb_vggsound_ep200
data.cutmix:
  desc: null
  value: 0
env.exclude:
  desc: null
  value: ''
env.workers:
  desc: null
  value: 2
opt.use_amp:
  desc: null
  value: false
data.dataset:
  desc: null
  value: vggsound
env.dist_url:
  desc: null
  value: tcp://localhost:50001
env.nodelist:
  desc: null
  value: node14
data.crop_min:
  desc: null
  value: 0.5
log.eval_freq:
  desc: null
  value: 10
log.save_freq:
  desc: null
  value: 50
log.use_wandb:
  desc: null
  value: true
opt.attn_drop:
  desc: null
  value: 0
opt.clip_grad:
  desc: null
  value: null
opt.drop_path:
  desc: null
  value: 0.2
opt.proj_drop:
  desc: null
  value: 0
opt.smoothing:
  desc: null
  value: 0.1
data.audio_dur:
  desc: null
  value: 3
data.data_path:
  desc: null
  value: /tmp/zverev/vggsound
encoder_prefix:
  desc: null
  value: encoder.
env.world_size:
  desc: null
  value: 4
log.print_freq:
  desc: null
  value: 100
opt.accum_iter:
  desc: null
  value: 4
opt.batch_size:
  desc: null
  value: 32
opt.joint_loss:
  desc: null
  value: true
data.audio_mels:
  desc: null
  value: 128
data.audio_rate:
  desc: null
  value: 16000
data.image_size:
  desc: null
  value: 224
data.mixup_mode:
  desc: null
  value: batch
data.mixup_prob:
  desc: null
  value: 1
env.distributed:
  desc: null
  value: true
opt.layer_decay:
  desc: null
  value: 0.75
env.dist_backend:
  desc: null
  value: nccl
env.slurm_suffix:
  desc: null
  value: ''
log.wandb_entity:
  desc: null
  value: audiovisual_diagnostics
opt.weight_decay:
  desc: null
  value: 0.05
env.slurm_comment:
  desc: null
  value: DeepAVFusion
env.slurm_timeout:
  desc: null
  value: 1440
log.wandb_project:
  desc: null
  value: efav
model.fusion.arch:
  desc: null
  value: factorized_mmi
opt.warmup_epochs:
  desc: null
  value: 20
pretrain_job_name:
  desc: null
  value: deepavfusion_vitb_vggsound_ep200
data.cutmix_minmax:
  desc: null
  value: null
env.slurm_partition:
  desc: null
  value: NORMAL
model.fusion.layers:
  desc: null
  value: all
log.wandb_watch_freq:
  desc: null
  value: 0
model.audio.backbone:
  desc: null
  value: vit_base
model.image.backbone:
  desc: null
  value: vit_base
pretrain_resume_epoch:
  desc: null
  value: latest
data.mixup_switch_prob:
  desc: null
  value: 0.5
model.audio.pretrained:
  desc: null
  value: vit_base_audiomae_as2m
model.fusion.mlp_ratio:
  desc: null
  value: 1
model.fusion.num_heads:
  desc: null
  value: 12
model.image.pretrained:
  desc: null
  value: vit_base_mae_in1k
model.fusion.attn_ratio:
  desc: null
  value: 0.25
model.fusion.num_fusion_tkns:
  desc: null
  value: 16
model.fusion.num_aggr_audio_tkns:
  desc: null
  value: 8
model.fusion.num_aggr_image_tkns:
  desc: null
  value: 8
