world_size: 1
rank: 0
dist_url: tcp://localhost:50001
dist_backend: nccl
port: 50001
node: localhost

distributed: True
seed:
gpu:
ngpu: 1
mem_gb:
workers: 8

slurm: True
slurm_suffix: ""
slurm_partition: NORMAL
slurm_comment: "DeepAVFusion"
slurm_timeout: 1440
nodelist: "node14"
exclude: ""
