world_size: 1
rank: 0
dist_url: tcp://localhost:50000
dist_backend: nccl
port: 50000
node: localhost

distributed: True
seed:
gpu:
ngpu: 1
mem_gb:
workers: 20

slurm: True
slurm_suffix: ""
slurm_partition: DEADLINE
slurm_comment: "CVPR"
slurm_timeout: 1440
nodelist: ""
exclude: ""
